"""add UserRecipes note, rating

Revision ID: 17652c9d018a
Revises: 2790b1c0d322
Create Date: 2025-06-18 18:01:04.454487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17652c9d018a'
down_revision: Union[str, None] = '2790b1c0d322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_recipes', sa.Column('note', sa.Text(), nullable=True, comment='ユーザーノート'))
    op.add_column('user_recipes', sa.Column('rating', sa.Integer(), nullable=True, comment='ユーザー評価 (1-5)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_recipes', 'rating')
    op.drop_column('user_recipes', 'note')
    # ### end Alembic commands ###
