"""add Recipe embedding

Revision ID: 2790b1c0d322
Revises: 67ae4c3ef5e0
Create Date: 2025-06-18 07:19:33.776503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '2790b1c0d322'
down_revision: Union[str, None] = '67ae4c3ef5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True, comment='レシピの埋め込みベクトル'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'embedding')
    # ### end Alembic commands ###
