"""add Recipe keyword genrue

Revision ID: 67ae4c3ef5e0
Revises: bdc0eb3a07cc
Create Date: 2025-06-17 17:10:13.733035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ae4c3ef5e0'
down_revision: Union[str, None] = 'bdc0eb3a07cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('keyword', sa.String(length=1024), nullable=True, comment='検索キーワード'))
    op.add_column('recipes', sa.Column('genrue', sa.String(length=256), nullable=True, comment='ジャンル'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'genrue')
    op.drop_column('recipes', 'keyword')
    # ### end Alembic commands ###
