"""change shopping list logic

Revision ID: 907af009db2e
Revises: 9ed71a1cf161
Create Date: 2025-06-20 00:34:53.317955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907af009db2e'
down_revision: Union[str, None] = '9ed71a1cf161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoppings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False, comment='レシピID'),
    sa.Column('list_name', sa.String(length=256), nullable=False, comment='買い物リスト名'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shoppings_id'), 'shoppings', ['id'], unique=False)
    op.add_column('user_shoppings', sa.Column('shopping_id', sa.Integer(), nullable=False, comment='レシピID'))
    op.add_column('user_shoppings', sa.Column('is_favorite', sa.Boolean(), nullable=True, comment='お気に入りフラグ'))
    op.drop_constraint('user_shoppings_recipe_id_fkey', 'user_shoppings', type_='foreignkey')
    op.create_foreign_key(None, 'user_shoppings', 'shoppings', ['shopping_id'], ['id'])
    op.drop_column('user_shoppings', 'recipe_id')
    op.drop_column('user_shoppings', 'list_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_shoppings', sa.Column('list_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False, comment='買い物リスト名'))
    op.add_column('user_shoppings', sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='レシピID'))
    op.drop_constraint(None, 'user_shoppings', type_='foreignkey')
    op.create_foreign_key('user_shoppings_recipe_id_fkey', 'user_shoppings', 'recipes', ['recipe_id'], ['id'])
    op.drop_column('user_shoppings', 'is_favorite')
    op.drop_column('user_shoppings', 'shopping_id')
    op.drop_index(op.f('ix_shoppings_id'), table_name='shoppings')
    op.drop_table('shoppings')
    # ### end Alembic commands ###
