"""add User

Revision ID: 9ed71a1cf161
Revises: 17652c9d018a
Create Date: 2025-06-19 00:48:07.603823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed71a1cf161'
down_revision: Union[str, None] = '17652c9d018a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('serving_size', sa.Integer(), nullable=True, comment='食べる人数'))
    op.add_column('users', sa.Column('salt_preference', sa.String(), nullable=True, comment='塩分の好み（low, normal, high）'))
    op.add_column('users', sa.Column('sweetness_preference', sa.String(), nullable=True, comment='甘さの好み（low, normal, high）'))
    op.add_column('users', sa.Column('spiciness_preference', sa.String(), nullable=True, comment='辛さの好み（low, normal, high）'))
    op.add_column('users', sa.Column('cooking_time_preference', sa.String(), nullable=True, comment='調理時間の好み'))
    op.add_column('users', sa.Column('meal_purpose', sa.String(), nullable=True, comment='食事の目的（breakfast, lunch, dinner, snack）'))
    op.add_column('users', sa.Column('disliked_ingredients', sa.Text(), nullable=True, comment='嫌いな食材（カンマ区切り）'))
    op.add_column('users', sa.Column('preference_trend', sa.Text(), nullable=True, comment='好みの傾向'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preference_trend')
    op.drop_column('users', 'disliked_ingredients')
    op.drop_column('users', 'meal_purpose')
    op.drop_column('users', 'cooking_time_preference')
    op.drop_column('users', 'spiciness_preference')
    op.drop_column('users', 'sweetness_preference')
    op.drop_column('users', 'salt_preference')
    op.drop_column('users', 'serving_size')
    # ### end Alembic commands ###
