"""create UserShopping ShoppingItem

Revision ID: bdc0eb3a07cc
Revises: 2dd1991b61fa
Create Date: 2025-06-17 12:50:35.325067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc0eb3a07cc'
down_revision: Union[str, None] = '2dd1991b61fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_shoppings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False, comment='レシピID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ユーザーID'),
    sa.Column('list_name', sa.String(length=256), nullable=False, comment='買い物リスト名'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_shoppings_id'), 'user_shoppings', ['id'], unique=False)
    op.create_table('shopping_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_shopping_id', sa.Integer(), nullable=False, comment='ユーザーショッピングID'),
    sa.Column('ingredient_id', sa.Integer(), nullable=False, comment='材料ID'),
    sa.Column('is_checked', sa.Boolean(), nullable=True, comment='チェック済みフラグ'),
    sa.Column('created_date', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_date', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['user_shopping_id'], ['user_shoppings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_items_id'), 'shopping_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_items_id'), table_name='shopping_items')
    op.drop_table('shopping_items')
    op.drop_index(op.f('ix_user_shoppings_id'), table_name='user_shoppings')
    op.drop_table('user_shoppings')
    # ### end Alembic commands ###
