"""change shopping item

Revision ID: efa7516f3e61
Revises: 907af009db2e
Create Date: 2025-06-20 00:46:11.000703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa7516f3e61'
down_revision: Union[str, None] = '907af009db2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_items', sa.Column('shopping_id', sa.Integer(), nullable=False, comment='ショッピングID'))
    op.add_column('shopping_items', sa.Column('ingredient', sa.String(length=256), nullable=False, comment='材料名'))
    op.drop_constraint('shopping_items_user_shopping_id_fkey', 'shopping_items', type_='foreignkey')
    op.drop_constraint('shopping_items_ingredient_id_fkey', 'shopping_items', type_='foreignkey')
    op.create_foreign_key(None, 'shopping_items', 'shoppings', ['shopping_id'], ['id'])
    op.drop_column('shopping_items', 'user_shopping_id')
    op.drop_column('shopping_items', 'ingredient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_items', sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='材料ID'))
    op.add_column('shopping_items', sa.Column('user_shopping_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ユーザーショッピングID'))
    op.drop_constraint(None, 'shopping_items', type_='foreignkey')
    op.create_foreign_key('shopping_items_ingredient_id_fkey', 'shopping_items', 'ingredients', ['ingredient_id'], ['id'])
    op.create_foreign_key('shopping_items_user_shopping_id_fkey', 'shopping_items', 'user_shoppings', ['user_shopping_id'], ['id'])
    op.drop_column('shopping_items', 'ingredient')
    op.drop_column('shopping_items', 'shopping_id')
    # ### end Alembic commands ###
