"""change shopping item

Revision ID: f22d6229620a
Revises: efa7516f3e61
Create Date: 2025-06-20 00:47:41.003505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22d6229620a'
down_revision: Union[str, None] = 'efa7516f3e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_items', sa.Column('amount', sa.String(length=64), nullable=True, comment='数量'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_items', 'amount')
    # ### end Alembic commands ###
