version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bae-recipe-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - ALLOWED_ORIGINS=http://localhost:5173
    volumes:
      - .:/app
    depends_on:
      - db
    command: sh -c "pip install -r requirements.dev.txt && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15
    container_name: bae-recipe-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bae_recipe
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: bae-recipe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: bae-recipe-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@baerecipe.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      

volumes:
  postgres_data:
  pgadmin_data:
  redis_data: