apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-genai-backend
  namespace: bae-recipe
  labels:
    app: aws-genai-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-genai-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: aws-genai-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/teamshackathon/prod/aws-genai-backend:latest
        imagePullPolicy: Always
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /api/v1/healthcheck/liveness
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/healthcheck/readiness
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
